---
- name: build AWS inventory report
  hosts: all
  gather_facts: False

  vars:
    #desired_version: "7.0(3)I7(1)"
    file_path: /var/www/html/generated_report.html

  tasks:
    - name: create HTML report
      template:
        src: report.j2
        dest: "{{ file_path }}"
      delegate_to: localhost
      run_once: true
